Console.WriteLine($"Solutions: ");
Console.WriteLine($"Day 1:\n  Part 1: {Day1.Part1()}\n  Part 2: {Day1.Part2()}\n");
Console.WriteLine($"Day 2:\n  Part 1: {Day2.Part1()}\n  Part 2: {Day2.Part2()}\n");
Console.WriteLine($"Day 3:\n  Part 1: {Day3.Part1()}\n  Part 2: {Day3.Part2()}\n");
Console.WriteLine($"Day 4:\n  Part 1: {Day4.Part1()}\n  Part 2: {Day4.Part2()}\n");
Console.WriteLine($"Day 5:\n  Part 1: {Day5.Part1()}\n  Part 2: {Day5.Part2()}\n");
Console.WriteLine($"Day 6:\n  Part 1: {Day6.Part1()}\n  Part 2: {Day6.Part2()}\n");
Console.WriteLine($"Day 7:\n  Part 1: {Day7.Part1()}\n  Part 2: {Day7.Part2()}\n");
Console.WriteLine($"Day 8:\n  Part 1: {Day8.Part1()}\n  Part 2: {Day8.Part2()}\n");
Console.WriteLine($"Day 9:\n  Part 1: {Day9.Part1()}\n  Part 2: {Day9_Part2.Part2()}\n");
Console.WriteLine($"Day 10:\n  Part 1: {Day10.Part1()}\n  Part 2: \n{Day10.Part2()}\n");